### ISSUE TITLE
operation non necessaire

### ISSUE THREAD

**Issue by elKokito** [mpsyco/inf4705#2]
RandomAccessIterator retourne déjà un pivot choisi aléatoirement non?

```
else {
      RandomAccessIterator mid = first + (last - first)/2; 
      pivot = median(*first, *mid, *(last-1));
    }  
```

**Comment by fstamour** [comment]
Non, `RandomAccessIterator` est simplement un itérateur qui peut accéder n'importe où n'importe quand, à l'opposé par exemple d'un `ForwardAccessIterator` qui ne peut qu'accéder aux éléments suivant (forward).

Ici on s'en sert pour avoir un "pointeur" sur le milieu, d'où le nom `mid`.

**Comment by fstamour** [comment]
(p-e que c'est `ForwardIterator` et non `ForwardAccessIterator`, mais j'ai pas le goût de regarde la doc :P)
